package:
  name: ray
  version: 2.42.0

source:
  url: https://files.pythonhosted.org/packages/54/1d/7338a8922fe39e4924d702c0bb70fe877f009e6437e59c86440f3e8d9ea2/ray-2.42.0-cp311-cp311-manylinux2014_x86_64.whl
  sha256: e8924b6ed086655b2bf8b3ff29ac453d1e8aa7a4d6d2ce965bbaa5fb17d1364f

build:
  noarch: python
    # script: pip install --no-deps --ignore-installed {{ environ.get('PKG_NAME') }}-{{ environ.get('PKG_VERSION') }}-*.whl
  number: 0

requirements:
  host:
    - python ==3.11
    - pip
  run:
    - python ==3.11
    - numpy  # Ray requires numpy, add more dependencies as needed

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  summary: "A framework for distributed computing."

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
  recipe-maintainers:
    - ianaobi
